/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.poo.practica05gui.vista.usuario;


import ec.edu.ups.poo.practica05gui.controlador.UsuarioControlador;
import ec.edu.ups.poo.practica05gui.modelo.Usuario;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ariel
 */
public class VentanaActualizarUsuario extends javax.swing.JInternalFrame {
    FondoVentana fondo = new FondoVentana();
    private UsuarioControlador usuarioControlador;
    /**
     * Creates new form VentanaActualizarUsuario
     */
    public VentanaActualizarUsuario(UsuarioControlador usuarioControlador) {
        this.setContentPane(fondo);
        initComponents();
        this.usuarioControlador = usuarioControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoVentana();
        nombreUsuario = new javax.swing.JLabel();
        txtActualizarCorreo = new javax.swing.JTextField();
        correoUsuario = new javax.swing.JLabel();
        txtActualizarNombre = new javax.swing.JTextField();
        IdentificaionUsuario = new javax.swing.JLabel();
        txtActualizarIdentificaion = new javax.swing.JTextField();
        btnBuscarActualizar = new javax.swing.JButton();
        btnCancelarActualizar = new javax.swing.JButton();
        btnGuardarActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizar Datos de Usuario");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Actualice su Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12))); // NOI18N

        nombreUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        nombreUsuario.setText("Nombre :");

        txtActualizarCorreo.setEditable(false);

        correoUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        correoUsuario.setText("Correo :");

        txtActualizarNombre.setEditable(false);

        IdentificaionUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        IdentificaionUsuario.setText("Identificacion  :");

        btnBuscarActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BuscarIcon.png"))); // NOI18N
        btnBuscarActualizar.setText("Buscar");
        btnBuscarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActualizarActionPerformed(evt);
            }
        });

        btnCancelarActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiarIcon.png"))); // NOI18N
        btnCancelarActualizar.setText("Cancelar");
        btnCancelarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActualizarActionPerformed(evt);
            }
        });

        btnGuardarActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardarIcon.png"))); // NOI18N
        btnGuardarActualizar.setText("Guardar");
        btnGuardarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(correoUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(txtActualizarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(IdentificaionUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(txtActualizarIdentificaion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nombreUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(txtActualizarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarActualizar)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardarActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarActualizar)
                        .addGap(168, 168, 168))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdentificaionUsuario)
                    .addComponent(txtActualizarIdentificaion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarActualizar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUsuario)
                    .addComponent(txtActualizarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoUsuario)
                    .addComponent(txtActualizarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarActualizar)
                    .addComponent(btnGuardarActualizar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActualizarActionPerformed
        String identificacion = txtActualizarIdentificaion.getText();
        Usuario usuario = usuarioControlador.buscarUsuario(identificacion);

        if (usuario==null){
            JOptionPane.showMessageDialog(this, "Usuario No Encontrado");
        }else{
            txtActualizarIdentificaion.setEditable(false);
            txtActualizarCorreo.setText(usuario.getCorreo());
            txtActualizarCorreo.setEditable(true);
            txtActualizarNombre.setText(usuario.getNombre());
            txtActualizarNombre.setEditable(true);
        }
    }//GEN-LAST:event_btnBuscarActualizarActionPerformed

    private void btnCancelarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActualizarActionPerformed
        limpiarDatos();
    }//GEN-LAST:event_btnCancelarActualizarActionPerformed

    private void btnGuardarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActualizarActionPerformed
        String identificaion = txtActualizarIdentificaion.getText();
        String nombre = txtActualizarNombre.getText();
        String correo =txtActualizarCorreo.getText();
                 
        usuarioControlador.actualizarUsuario(correo, nombre, identificaion);
        JOptionPane.showMessageDialog(this, "Usuario Actualizado Exitosamente");
        limpiarDatos();
    }//GEN-LAST:event_btnGuardarActualizarActionPerformed
    private void limpiarDatos(){
        txtActualizarCorreo.setEditable(false);
        txtActualizarNombre.setEditable(false);      
        txtActualizarIdentificaion.setEditable(true);
        txtActualizarIdentificaion.setText("");
        txtActualizarCorreo.setText("");
        txtActualizarNombre.setText("");      
    }
    public void cambiarIdioma(Locale locale)
    {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes",locale); 
        IdentificaionUsuario.setText(mensajes.getString("IdentificaionUsuario"));
        nombreUsuario.setText(mensajes.getString("nombreUsuario"));
        correoUsuario.setText(mensajes.getString("correoUsuario"));
        btnBuscarActualizar.setText(mensajes.getString("btnBuscarActualizar"));  
        btnGuardarActualizar.setText(mensajes.getString("btnGuardarActualizar"));
        btnCancelarActualizar.setText(mensajes.getString("btnCancelarActualizar"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdentificaionUsuario;
    private javax.swing.JButton btnBuscarActualizar;
    private javax.swing.JButton btnCancelarActualizar;
    private javax.swing.JButton btnGuardarActualizar;
    private javax.swing.JLabel correoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JTextField txtActualizarCorreo;
    private javax.swing.JTextField txtActualizarIdentificaion;
    private javax.swing.JTextField txtActualizarNombre;
    // End of variables declaration//GEN-END:variables

    class FondoVentana extends JPanel      
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon (getClass().getResource("/imagenes/fondoSecundario.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g); 
        }
    }
}
