/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.poo.practica05gui.vista.usuario;


import ec.edu.ups.poo.practica05gui.controlador.UsuarioControlador;
import ec.edu.ups.poo.practica05gui.modelo.Usuario;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ariel
 */
public class VentanaEliminarUsuario extends javax.swing.JInternalFrame {
    FondoVentana fondo = new FondoVentana();
    private UsuarioControlador usuarioControlador;
    /**
     * Creates new form VentanaEliminarUsuario
     */
    public VentanaEliminarUsuario(UsuarioControlador usuarioControlador) {
        this.setContentPane(fondo);
        initComponents();
        this.usuarioControlador = usuarioControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoVentana();
        IdentificaionUsuario = new javax.swing.JLabel();
        txtEliminarIdentificaion = new javax.swing.JTextField();
        nombreUsuario = new javax.swing.JLabel();
        txtEliminarNombre = new javax.swing.JTextField();
        correoUsuario = new javax.swing.JLabel();
        txtEliminarCorreo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnBuscarEliminar = new javax.swing.JButton();
        btnCancelarEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar Datos de Usuario");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Eliminar Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12))); // NOI18N

        IdentificaionUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        IdentificaionUsuario.setText("Identificacion :");

        nombreUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        nombreUsuario.setText("Nombre :");

        txtEliminarNombre.setEditable(false);

        correoUsuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        correoUsuario.setText("Correo :");

        txtEliminarCorreo.setEditable(false);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarIcon.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscarEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BuscarIcon.png"))); // NOI18N
        btnBuscarEliminar.setText("Buscar");
        btnBuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEliminarActionPerformed(evt);
            }
        });

        btnCancelarEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiarIcon.png"))); // NOI18N
        btnCancelarEliminar.setText("Cancelar");
        btnCancelarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(IdentificaionUsuario))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(correoUsuario, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEliminarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEliminarIdentificaion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarEliminar))
                            .addComponent(txtEliminarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarEliminar)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdentificaionUsuario)
                    .addComponent(txtEliminarIdentificaion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUsuario)
                    .addComponent(txtEliminarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoUsuario)
                    .addComponent(txtEliminarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEliminar)
                    .addComponent(btnEliminar))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int respuesta= JOptionPane.showConfirmDialog(this, "¿Esta Seguro?");
        if (respuesta == JOptionPane.YES_OPTION){
            String identificaion=txtEliminarIdentificaion.getText();
            String nombre = txtEliminarNombre.getText();
            String correo =txtEliminarCorreo.getText();

            usuarioControlador.eliminarUsuario(identificaion);
            JOptionPane.showMessageDialog(this, "Usuario Eliminado Exitosamente");
            limpiarDatos();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarActionPerformed
        String identificaion = txtEliminarIdentificaion.getText();
        Usuario usuario = usuarioControlador.buscarUsuario(identificaion);

        if (usuario==null){
            JOptionPane.showMessageDialog(this, "Usuario No Encontrado");
        }else{
            txtEliminarIdentificaion.setEditable(false);
            txtEliminarCorreo.setText(usuario.getCorreo());
            txtEliminarCorreo.setEditable(true);
            txtEliminarNombre.setText(usuario.getNombre());
            txtEliminarNombre.setEditable(true);
        }
    }//GEN-LAST:event_btnBuscarEliminarActionPerformed

    private void btnCancelarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEliminarActionPerformed
        limpiarDatos();
    }//GEN-LAST:event_btnCancelarEliminarActionPerformed
    private void limpiarDatos(){
        txtEliminarCorreo.setEditable(false);
        txtEliminarNombre.setEditable(false);       
        txtEliminarIdentificaion.setEditable(true);
        txtEliminarIdentificaion.setText("");
        txtEliminarCorreo.setText("");
        txtEliminarNombre.setText("");        
    }
    public void cambiarIdioma(Locale locale)
    {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes",locale); 
        IdentificaionUsuario.setText(mensajes.getString("IdentificaionUsuario"));
        nombreUsuario.setText(mensajes.getString("nombreUsuario"));
        correoUsuario.setText(mensajes.getString("correoUsuario"));
        btnBuscarEliminar.setText(mensajes.getString("btnBuscarEliminar"));
        btnEliminar.setText(mensajes.getString("btnEliminar"));
        btnCancelarEliminar.setText(mensajes.getString("btnCancelarEliminar"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdentificaionUsuario;
    private javax.swing.JButton btnBuscarEliminar;
    private javax.swing.JButton btnCancelarEliminar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel correoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JTextField txtEliminarCorreo;
    private javax.swing.JTextField txtEliminarIdentificaion;
    private javax.swing.JTextField txtEliminarNombre;
    // End of variables declaration//GEN-END:variables

    class FondoVentana extends JPanel      
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon (getClass().getResource("/imagenes/fondoSecundario.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g); 
        }
    }
}
