/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.poo.practica05gui.vista.biblioteca;

import ec.edu.ups.poo.practica05gui.controlador.BibliotecaControlador;
import ec.edu.ups.poo.practica05gui.modelo.Biblioteca;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ESTUDIANTE
 */
public class VentanaEliminarBiblioteca extends javax.swing.JInternalFrame {
    FondoVentana fondo = new FondoVentana();
    private BibliotecaControlador bibliotecaControlador;
    /**
     * Creates new form VentanaCrearBiblioteca
     */
    public VentanaEliminarBiblioteca(BibliotecaControlador bibliotecaControlador) {
        this.setContentPane(fondo);
        initComponents();
        this.bibliotecaControlador=bibliotecaControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoVentana();
        direccionBiblioteca = new javax.swing.JLabel();
        txtDireccionBiblioteca = new javax.swing.JTextField();
        telefonoBiblioteca = new javax.swing.JLabel();
        txtTelefonoBiblioteca = new javax.swing.JTextField();
        btnEliminarBiblioteca = new javax.swing.JButton();
        codigoBiblioteca = new javax.swing.JLabel();
        txtCodigoBiblioteca = new javax.swing.JTextField();
        nombreBiblioteca = new javax.swing.JLabel();
        txtNombreBiblioteca = new javax.swing.JTextField();
        btnLimpiarBiblioteca = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar Biblioteca");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        direccionBiblioteca.setText("Direccion");

        txtDireccionBiblioteca.setEditable(false);

        telefonoBiblioteca.setText("Telefono");

        txtTelefonoBiblioteca.setEditable(false);

        btnEliminarBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarIcon.png"))); // NOI18N
        btnEliminarBiblioteca.setText("Eliminar");
        btnEliminarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBibliotecaActionPerformed(evt);
            }
        });

        codigoBiblioteca.setText("Codigo");

        nombreBiblioteca.setText("Nombre");

        txtNombreBiblioteca.setEditable(false);

        btnLimpiarBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiarIcon.png"))); // NOI18N
        btnLimpiarBiblioteca.setText("Limpiar");
        btnLimpiarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBibliotecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiarBiblioteca)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codigoBiblioteca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigoBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nombreBiblioteca)
                                .addGap(42, 42, 42)
                                .addComponent(txtNombreBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(direccionBiblioteca)
                                    .addComponent(telefonoBiblioteca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccionBiblioteca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoBiblioteca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarBiblioteca)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoBiblioteca)
                    .addComponent(txtCodigoBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarBiblioteca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreBiblioteca)
                    .addComponent(txtNombreBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionBiblioteca)
                    .addComponent(txtDireccionBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoBiblioteca)
                    .addComponent(txtTelefonoBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarBiblioteca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBibliotecaActionPerformed
        if (txtCodigoBiblioteca.getText().isBlank())
        {
            JOptionPane.showMessageDialog(this, "No ha ingresado un codigo");
        }else
        {
            int codigo = Integer.parseInt(txtCodigoBiblioteca.getText());
            Biblioteca biblioteca = bibliotecaControlador.read(codigo);
            if (biblioteca!=null)
            {
                txtNombreBiblioteca.setText(biblioteca.getNombre());
                txtDireccionBiblioteca.setText(biblioteca.getDireccion());
                txtTelefonoBiblioteca.setText(biblioteca.getTelefono()); 
                int i = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar la Biblioteca?");
                if(i==0)
                {
                    bibliotecaControlador.delete(codigo);
                    JOptionPane.showMessageDialog(this,"Se ha eliminado la Biblioteca");
                    limpiarDatos();
                }
                else if (i==1)
                {
                    JOptionPane.showMessageDialog(this,"No se ha eliminado la Biblioteca");
                }

            }else
                {
                    JOptionPane.showMessageDialog(this,"No existe una Biblioteca con tal codigo");
                }
            }
    }//GEN-LAST:event_btnEliminarBibliotecaActionPerformed

    private void btnLimpiarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBibliotecaActionPerformed
        limpiarDatos();
    }//GEN-LAST:event_btnLimpiarBibliotecaActionPerformed
    
    private void limpiarDatos()
    {
        txtCodigoBiblioteca.setText("");
        txtNombreBiblioteca.setText("");
        txtDireccionBiblioteca.setText("");
        txtTelefonoBiblioteca.setText("");    
    }
    public void cambiarIdioma(Locale locale)
    {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes",locale); 
        codigoBiblioteca.setText(mensajes.getString("codigoBiblioteca"));
        nombreBiblioteca.setText(mensajes.getString("nombreBiblioteca"));
        direccionBiblioteca.setText(mensajes.getString("direccionBiblioteca"));
        telefonoBiblioteca.setText(mensajes.getString("telefonoBiblioteca"));
        btnEliminarBiblioteca.setText(mensajes.getString("btnEliminarBiblioteca"));
        btnLimpiarBiblioteca.setText(mensajes.getString("btnLimpiarBiblioteca"));
        this.setTitle(mensajes.getString("eliminarBibliotecaMenuItem"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarBiblioteca;
    private javax.swing.JButton btnLimpiarBiblioteca;
    private javax.swing.JLabel codigoBiblioteca;
    private javax.swing.JLabel direccionBiblioteca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreBiblioteca;
    private javax.swing.JLabel telefonoBiblioteca;
    private javax.swing.JTextField txtCodigoBiblioteca;
    private javax.swing.JTextField txtDireccionBiblioteca;
    private javax.swing.JTextField txtNombreBiblioteca;
    private javax.swing.JTextField txtTelefonoBiblioteca;
    // End of variables declaration//GEN-END:variables

    class FondoVentana extends JPanel      
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon (getClass().getResource("/imagenes/fondoSecundario.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g); 
        }
    }
}
