/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.poo.practica05gui.vista.prestamo;

import ec.edu.ups.poo.practica05gui.controlador.PrestamoControlador;
import ec.edu.ups.poo.practica05gui.modelo.Biblioteca;
import ec.edu.ups.poo.practica05gui.modelo.Libro;
import ec.edu.ups.poo.practica05gui.modelo.Prestamo;
import ec.edu.ups.poo.practica05gui.modelo.Usuario;
import java.awt.Graphics;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sebas
 */
public class VentanaEditarPrestamo extends javax.swing.JInternalFrame {
    FondoVentana fondo = new FondoVentana();
    private PrestamoControlador prestamoControlador;
    public VentanaEditarPrestamo(PrestamoControlador prestamoControlador) {
        this.setContentPane(fondo);
        initComponents();
        this.prestamoControlador = prestamoControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new FondoVentana();
        datoFechaPrestamo = new com.toedter.calendar.JDateChooser();
        fechaPrestamo = new javax.swing.JLabel();
        btnBuscarPrestamo = new javax.swing.JButton();
        fechaDevPrestamo = new javax.swing.JLabel();
        libroPrestamo = new javax.swing.JLabel();
        identificaionPrestamo = new javax.swing.JLabel();
        btnEditarPrestamo = new javax.swing.JButton();
        datoFechaDevolucion = new com.toedter.calendar.JDateChooser();
        bibliotecaPrestamo = new javax.swing.JLabel();
        comboBibliotecas = new javax.swing.JComboBox<>();
        comboLibros = new javax.swing.JComboBox<>();
        comboUsuarios = new javax.swing.JComboBox<>();
        codigoPrestamo = new javax.swing.JLabel();
        txtCodigoPrestamo = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Prestamo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Datos"));

        datoFechaPrestamo.setEnabled(false);

        fechaPrestamo.setText("Fecha Prestamo");

        btnBuscarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BuscarIcon.png"))); // NOI18N
        btnBuscarPrestamo.setText("Buscar");
        btnBuscarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamoActionPerformed(evt);
            }
        });

        fechaDevPrestamo.setText("Fecha Devolucion");

        libroPrestamo.setText("Libro");

        identificaionPrestamo.setText("Usuario Identificacion");

        btnEditarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardarIcon.png"))); // NOI18N
        btnEditarPrestamo.setText("Guardar");
        btnEditarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPrestamoActionPerformed(evt);
            }
        });

        datoFechaDevolucion.setEnabled(false);

        bibliotecaPrestamo.setText("Biblioteca");

        comboBibliotecas.setEnabled(false);

        comboLibros.setEnabled(false);

        comboUsuarios.setEnabled(false);

        codigoPrestamo.setText("Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaPrestamo)
                            .addComponent(fechaDevPrestamo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(identificaionPrestamo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(libroPrestamo))
                            .addComponent(bibliotecaPrestamo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(codigoPrestamo)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCodigoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPrestamo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(datoFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(datoFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboUsuarios, javax.swing.GroupLayout.Alignment.LEADING, 0, 131, Short.MAX_VALUE)
                        .addComponent(comboLibros, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBibliotecas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEditarPrestamo))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bibliotecaPrestamo)
                    .addComponent(comboBibliotecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libroPrestamo)
                    .addComponent(comboLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificaionPrestamo)
                    .addComponent(comboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaPrestamo)
                    .addComponent(datoFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaDevPrestamo)
                    .addComponent(datoFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoPrestamo)
                    .addComponent(btnBuscarPrestamo)
                    .addComponent(txtCodigoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnEditarPrestamo)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamoActionPerformed
    int codigo = Integer.parseInt(txtCodigoPrestamo.getText());
    
    if(datoFechaPrestamo==null)
    {
        JOptionPane.showMessageDialog(this, "No ha ingresado una fecha");
    }else
    {
        Prestamo prestamo =  prestamoControlador.read(codigo);
        if(prestamo!=null)
        {
            datoFechaDevolucion.setDate(prestamo.getFechaDevolucion());
            datoFechaPrestamo.setDate(prestamo.getFechaPrestamo());
            datoFechaDevolucion.setEnabled(true);
            datoFechaPrestamo.setEnabled(true);
            comboBibliotecas.setEnabled(true);
            comboLibros.setEnabled(true);
            comboUsuarios.setEnabled(true);
            cargarComboBiblioteca(comboBibliotecas);
            cargarComboLibro(comboLibros);
            cargarComboUsuario(comboUsuarios);
            txtCodigoPrestamo.setEditable(false);
        }else
        {
            JOptionPane.showMessageDialog(this, "No hay prestamo con tal fecha");
        }        
    }
    }//GEN-LAST:event_btnBuscarPrestamoActionPerformed

    private void btnEditarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPrestamoActionPerformed
        if (comboBibliotecas.getSelectedItem()==null||comboUsuarios.getSelectedItem()==null||comboLibros.getSelectedItem()==null||datoFechaPrestamo.toString().isBlank()||datoFechaDevolucion.toString().isBlank())
        {
            JOptionPane.showMessageDialog(this, "No se han ingresado todos los datos");            
        }else
        {

            String titulo = comboLibros.getSelectedItem().toString();
            String identificacion = comboUsuarios.getSelectedItem().toString();        
            int codigo = Integer.parseInt(txtCodigoPrestamo.getText());
            Libro libro = prestamoControlador.readLibro(titulo);
            Usuario usuario = prestamoControlador.readUsuario(identificacion);
            Date fechaPrestamo = datoFechaPrestamo.getDate();
            Date fechaDevolucion = datoFechaDevolucion.getDate();
            Prestamo prestamo = new Prestamo(codigo,libro, usuario, fechaPrestamo, fechaDevolucion);
            prestamoControlador.update(codigo, prestamo);
            JOptionPane.showMessageDialog(this, "Prestamo actualizado correctamemte"); 
        }        
    }//GEN-LAST:event_btnEditarPrestamoActionPerformed
    private void cargarComboBiblioteca(JComboBox c)
    {
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        c.setModel(combo);
        List<Biblioteca> bibliotecas = prestamoControlador.toListBiblioteca();
        for(Biblioteca biblioteca : bibliotecas)
        {
            combo.addElement(biblioteca.getCodigo());
        }     
    }

    private void cargarComboLibro(JComboBox c)
    {
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        c.setModel(combo);
        List<Libro> libros = prestamoControlador.toListLibro();
        for(Libro libro : libros)
        {
            combo.addElement(libro.getTitulo());
        }
        
    }
    
    private void cargarComboUsuario(JComboBox c)
    {
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        c.setModel(combo);
        List<Usuario> usuarios = prestamoControlador.toListUsuario();
        for(Usuario usuario : usuarios)
        {
            combo.addElement(usuario.getIdentificacion());
        }        
    }
    public void cambiarIdioma(Locale locale)
    {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes",locale); 
        bibliotecaPrestamo.setText(mensajes.getString("bibliotecaPrestamo"));
        libroPrestamo.setText(mensajes.getString("libroPrestamo"));
        identificaionPrestamo.setText(mensajes.getString("identificaionPrestamo"));
        fechaPrestamo.setText(mensajes.getString("fechaPrestamo"));
        fechaDevPrestamo.setText(mensajes.getString("fechaDevPrestamo"));  
        codigoPrestamo.setText(mensajes.getString("codigoPrestamo"));
        btnBuscarPrestamo.setText(mensajes.getString("btnBuscarPrestamo"));
        btnEditarPrestamo.setText(mensajes.getString("btnEditarPrestamo"));
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bibliotecaPrestamo;
    private javax.swing.JButton btnBuscarPrestamo;
    private javax.swing.JButton btnEditarPrestamo;
    private javax.swing.JLabel codigoPrestamo;
    private javax.swing.JComboBox<String> comboBibliotecas;
    private javax.swing.JComboBox<String> comboLibros;
    private javax.swing.JComboBox<String> comboUsuarios;
    private com.toedter.calendar.JDateChooser datoFechaDevolucion;
    private com.toedter.calendar.JDateChooser datoFechaPrestamo;
    private javax.swing.JLabel fechaDevPrestamo;
    private javax.swing.JLabel fechaPrestamo;
    private javax.swing.JLabel identificaionPrestamo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel libroPrestamo;
    private javax.swing.JTextField txtCodigoPrestamo;
    // End of variables declaration//GEN-END:variables

    class FondoVentana extends JPanel      
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon (getClass().getResource("/imagenes/fondoSecundario.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g); 
        }
    }
}
