package ec.edu.ups.poo.practica05gui.vista.prestamo;

import ec.edu.ups.poo.practica05gui.controlador.PrestamoControlador;
import ec.edu.ups.poo.practica05gui.modelo.Biblioteca;
import ec.edu.ups.poo.practica05gui.modelo.Libro;
import ec.edu.ups.poo.practica05gui.modelo.Usuario;
import java.awt.Graphics;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sebas
 */
public class VentanaPrestarPrestamo extends javax.swing.JInternalFrame {
    FondoVentana fondo = new FondoVentana();
    private PrestamoControlador prestamoControlador;
    
    public VentanaPrestarPrestamo(PrestamoControlador prestamoControlador) {
        this.setContentPane(fondo);
        initComponents();
        this.prestamoControlador = prestamoControlador;
        cargarComboBiblioteca(comboBibliotecas);
        cargarComboUsuario(comboUsuarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new FondoVentana();
        bibliotecaPrestamo = new javax.swing.JLabel();
        comboBibliotecas = new javax.swing.JComboBox<>();
        libroPrestamo = new javax.swing.JLabel();
        comboLibros = new javax.swing.JComboBox<>();
        comboUsuarios = new javax.swing.JComboBox<>();
        identificaionPrestamo = new javax.swing.JLabel();
        btnPrestar = new javax.swing.JButton();
        datoFechaPrestamo = new com.toedter.calendar.JDateChooser();
        datoFechaDevolucion = new com.toedter.calendar.JDateChooser();
        fechaPrestamo = new javax.swing.JLabel();
        fechaDevPrestamo = new javax.swing.JLabel();
        codigoPrestamo = new javax.swing.JLabel();
        txtCodigoPrestamo = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Realizar Prestamo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Datos"));

        bibliotecaPrestamo.setText("Biblioteca");

        comboBibliotecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBibliotecasActionPerformed(evt);
            }
        });

        libroPrestamo.setText("Libro");

        identificaionPrestamo.setText("Usuario Identificacion");

        btnPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardarIcon.png"))); // NOI18N
        btnPrestar.setText("Prestar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        fechaPrestamo.setText("Fecha Prestamo");

        fechaDevPrestamo.setText("Fecha Devolucion");

        codigoPrestamo.setText("Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnPrestar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(identificaionPrestamo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(libroPrestamo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(bibliotecaPrestamo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fechaDevPrestamo)
                                    .addComponent(fechaPrestamo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(codigoPrestamo)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datoFechaDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(datoFechaPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comboLibros, 0, 125, Short.MAX_VALUE)
                                        .addComponent(comboUsuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboBibliotecas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtCodigoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bibliotecaPrestamo)
                    .addComponent(comboBibliotecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libroPrestamo)
                    .addComponent(comboLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identificaionPrestamo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datoFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaPrestamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datoFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaDevPrestamo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoPrestamo)
                    .addComponent(txtCodigoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrestar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBibliotecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBibliotecasActionPerformed
    
        int codigo = Integer.parseInt(comboBibliotecas.getSelectedItem().toString());
        
        for(Biblioteca biblioteca : prestamoControlador.toListBiblioteca())
        {
            if (biblioteca.getCodigo()==codigo)
            {
                cargarComboLibro(comboLibros);
            }
        }
    }//GEN-LAST:event_comboBibliotecasActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        if (comboBibliotecas.getSelectedItem()==null||comboUsuarios.getSelectedItem()==null||comboLibros.getSelectedItem()==null||txtCodigoPrestamo.getText().isBlank()||datoFechaPrestamo.toString().isBlank()||datoFechaDevolucion.toString().isBlank())
        {
            JOptionPane.showMessageDialog(this, "No se han ingresado todos los datos");            
        }else
        {
            String titulo = comboLibros.getSelectedItem().toString();
            String identificacion = comboUsuarios.getSelectedItem().toString();        

            Libro libro = prestamoControlador.readLibro(titulo);
            Usuario usuario = prestamoControlador.readUsuario(identificacion);
            Date fechaPrestamo = datoFechaPrestamo.getDate();
            Date fechaDevolucion = datoFechaDevolucion.getDate();
            int codigo = Integer.parseInt(txtCodigoPrestamo.getText());
            prestamoControlador.create(codigo,libro, usuario, fechaPrestamo, fechaDevolucion);
            JOptionPane.showMessageDialog(this, "Prestamo realizado correctamemte"); 
        }
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void cargarComboBiblioteca(JComboBox c)
    {
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        c.setModel(combo);
        List<Biblioteca> bibliotecas = prestamoControlador.toListBiblioteca();
        for(Biblioteca biblioteca : bibliotecas)
        {
            combo.addElement(biblioteca.getCodigo());
        }     
    }

    private void cargarComboLibro(JComboBox c)
    {
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        c.setModel(combo);
        List<Libro> libros = prestamoControlador.toListLibro();
        for(Libro libro : libros)
        {
            combo.addElement(libro.getTitulo());
        }
        
    }
    
    private void cargarComboUsuario(JComboBox c)
    {
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        c.setModel(combo);
        List<Usuario> usuarios = prestamoControlador.toListUsuario();
        for(Usuario usuario : usuarios)
        {
            combo.addElement(usuario.getIdentificacion());
        }        
    }
    public void cambiarIdioma(Locale locale)
    {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes",locale); 
        bibliotecaPrestamo.setText(mensajes.getString("bibliotecaPrestamo"));
        libroPrestamo.setText(mensajes.getString("libroPrestamo"));
        identificaionPrestamo.setText(mensajes.getString("identificaionPrestamo"));
        fechaPrestamo.setText(mensajes.getString("fechaPrestamo"));
        fechaDevPrestamo.setText(mensajes.getString("fechaDevPrestamo"));  
        codigoPrestamo.setText(mensajes.getString("codigoPrestamo"));
        btnPrestar.setText(mensajes.getString("btnPrestar"));
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bibliotecaPrestamo;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JLabel codigoPrestamo;
    private javax.swing.JComboBox<String> comboBibliotecas;
    private javax.swing.JComboBox<String> comboLibros;
    private javax.swing.JComboBox<String> comboUsuarios;
    private com.toedter.calendar.JDateChooser datoFechaDevolucion;
    private com.toedter.calendar.JDateChooser datoFechaPrestamo;
    private javax.swing.JLabel fechaDevPrestamo;
    private javax.swing.JLabel fechaPrestamo;
    private javax.swing.JLabel identificaionPrestamo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel libroPrestamo;
    private javax.swing.JTextField txtCodigoPrestamo;
    // End of variables declaration//GEN-END:variables

    class FondoVentana extends JPanel      
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon (getClass().getResource("/imagenes/fondoSecundario.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g); 
        }
    }
}
