/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.poo.practica05gui.vista.prestamo;

import ec.edu.ups.poo.practica05gui.controlador.PrestamoControlador;
import ec.edu.ups.poo.practica05gui.modelo.Libro;
import ec.edu.ups.poo.practica05gui.modelo.Prestamo;
import java.awt.Graphics;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class VentanaListarPrestamo extends javax.swing.JInternalFrame {
    FondoVentana fondo = new FondoVentana();
    private PrestamoControlador prestamoControlador;
    /**
     * Creates new form VentanaListarPrestamo
     */
    public VentanaListarPrestamo(PrestamoControlador prestamoControlador) {
        this.setContentPane(fondo);
        initComponents();
        this.prestamoControlador=prestamoControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatosPrestamo = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listar Prestamos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tablaDatosPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Libro", "Usuario", "Fecha Prestamo", "Fecha Devolucion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDatosPrestamo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void cargarDatos(){
    List<Prestamo> prestamos = prestamoControlador.toListPrestamo();
    DefaultTableModel modelo = (DefaultTableModel) tablaDatosPrestamo.getModel();
    modelo.setNumRows(0);
    for (Prestamo prestamo : prestamos){
        Object[] rowData ={prestamo.getCodigo(), prestamo.getLibro(), prestamo.getUsuario(), prestamo.getFechaPrestamo(), prestamo.getFechaDevolucion()};
        modelo.addRow(rowData);
    }
}

public void limpiarTabla(){
        try{
            DefaultTableModel modelo = (DefaultTableModel) tablaDatosPrestamo.getModel();
                int a =modelo.getRowCount()-1;
                for(int i=0; i<a; i++)
                        modelo.removeRow(0);
            }catch(Exception e){
                System.out.println(e);
            }
}
public void cambiarIdioma(Locale locale)
    {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes",locale); 
        String codigo = (mensajes.getString("codigoBiblioteca"));
        String libro = (mensajes.getString("libroPrestamo"));
        String usuario = (mensajes.getString("usuarioMenu"));
        String fechaP = (mensajes.getString("fechaPrestamo"));
        String fechaD = (mensajes.getString("fechaDevPrestamo"));
        DefaultTableModel tabla = (DefaultTableModel) tablaDatosPrestamo.getModel();
        tabla.setColumnIdentifiers(new String [] {codigo, libro, usuario, fechaP, fechaD});
        this.setTitle(mensajes.getString("ListarP"));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatosPrestamo;
    // End of variables declaration//GEN-END:variables

    class FondoVentana extends JPanel      
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon (getClass().getResource("/imagenes/fondoSecundario.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g); 
        }
    }
}
