package ec.edu.ups.poo.practica05gui.vista.libro;

import ec.edu.ups.poo.practica05gui.controlador.*;
import ec.edu.ups.poo.practica05gui.modelo.Biblioteca;
import ec.edu.ups.poo.practica05gui.modelo.Libro;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class VentanaCrearLibro extends javax.swing.JInternalFrame {
    FondoVentana fondo = new FondoVentana();
    private LibroControlador libroControlador;
    /**
     * Creates new form VentanaCrearLibro
     */
    public VentanaCrearLibro(LibroControlador libroControlador) {
        this.setContentPane(fondo);
        initComponents();
        this.libroControlador=libroControlador;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoVentana();
        codigoLibro = new javax.swing.JLabel();
        tituloLibro = new javax.swing.JLabel();
        autorLibro = new javax.swing.JLabel();
        anioLibro = new javax.swing.JLabel();
        txtCodigoLibro = new javax.swing.JTextField();
        txtAutorLibro = new javax.swing.JTextField();
        txtTituloLibro = new javax.swing.JTextField();
        txtAnioLibro = new javax.swing.JTextField();
        btnCrearLibro = new javax.swing.JButton();
        codigoBiblioteca = new javax.swing.JLabel();
        comboBibliotecas = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Crear Nuevo Libro");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        codigoLibro.setText("Codigo");

        tituloLibro.setText("Titulo");

        autorLibro.setText("Autor");

        anioLibro.setText("Anio Publicacion");

        btnCrearLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardarIcon.png"))); // NOI18N
        btnCrearLibro.setText("Guardar");
        btnCrearLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearLibroActionPerformed(evt);
            }
        });

        codigoBiblioteca.setText("Codigo Biblioteca");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrearLibro)
                .addGap(146, 146, 146))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(codigoLibro)
                            .addComponent(tituloLibro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(autorLibro, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(anioLibro))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(codigoBiblioteca)))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAnioLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(txtCodigoLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(txtAutorLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(txtTituloLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(comboBibliotecas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLibro)
                    .addComponent(txtCodigoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloLibro)
                    .addComponent(txtTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autorLibro)
                    .addComponent(txtAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anioLibro)
                    .addComponent(txtAnioLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoBiblioteca)
                    .addComponent(comboBibliotecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearLibro)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLibroActionPerformed
        if (txtCodigoLibro.getText().isBlank()||txtTituloLibro.getText().isBlank()||txtAutorLibro.getText().isBlank()||txtAnioLibro.getText().isBlank())
        {
            JOptionPane.showMessageDialog(this, "Rellene todos los atributos");
        }else
        {
            int codigo = Integer.parseInt(txtCodigoLibro.getText());
            Libro libro = libroControlador.read1(codigo);
            if (libro!=null)
            {
                JOptionPane.showMessageDialog(this, "Ya existe un libro con ese codigo");
                txtCodigoLibro.setText("");
                txtTituloLibro.setText("");
                txtAutorLibro.setText("");
                txtAnioLibro.setText("");                   
            }else
            {
            String titulo = txtTituloLibro.getText();
            String autor = txtAutorLibro.getText();
            int anio = Integer.parseInt(txtAnioLibro.getText());
            boolean disponible = true;
            
            if(comboBibliotecas.getSelectedItem().toString().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Biblioteca no valida");
            }else
            {
                int codigoBiblioteca = Integer.parseInt(comboBibliotecas.getSelectedItem().toString());
                libroControlador.create(codigo, titulo, autor, anio, disponible);
            }            
            
            JOptionPane.showMessageDialog(this, "Se han guardado los datos");
            
            txtCodigoLibro.setText("");
            txtTituloLibro.setText("");
            txtAutorLibro.setText("");
            txtAnioLibro.setText("");    
            }
        }
    }//GEN-LAST:event_btnCrearLibroActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarComboBiblioteca(comboBibliotecas);
    }//GEN-LAST:event_formInternalFrameActivated

    private void cargarComboBiblioteca(JComboBox c)
    {
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        c.setModel(combo);
        List<Biblioteca> bibliotecas = libroControlador.toListBiblioteca();
        for(Biblioteca biblioteca : bibliotecas)
        {
            combo.addElement(biblioteca.getCodigo());
        }     
    }
    public void cambiarIdioma(Locale locale)
    {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes",locale); 
        codigoLibro.setText(mensajes.getString("codigoLibro"));
        tituloLibro.setText(mensajes.getString("tituloLibro"));
        autorLibro.setText(mensajes.getString("autorLibro"));
        anioLibro.setText(mensajes.getString("anioLibro"));  
        codigoBiblioteca.setText(mensajes.getString("codigoBiblioteca"));  
        btnCrearLibro.setText(mensajes.getString("btnCrearLibro"));   
        this.setTitle(mensajes.getString("crearLibroMenuItem1"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anioLibro;
    private javax.swing.JLabel autorLibro;
    private javax.swing.JButton btnCrearLibro;
    private javax.swing.JLabel codigoBiblioteca;
    private javax.swing.JLabel codigoLibro;
    private javax.swing.JComboBox<String> comboBibliotecas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloLibro;
    private javax.swing.JTextField txtAnioLibro;
    private javax.swing.JTextField txtAutorLibro;
    private javax.swing.JTextField txtCodigoLibro;
    private javax.swing.JTextField txtTituloLibro;
    // End of variables declaration//GEN-END:variables

    class FondoVentana extends JPanel      
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon (getClass().getResource("/imagenes/fondoSecundario.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g); 
        }
    }
}
